apiVersion: v1
kind: Service
metadata:
  name: devopsdozo-db
  namespace: devopsdozo
  labels:
    service: database
spec:
  type: ExternalName
  externalName:  bootcamp-dev-db.cvik8accw2tk.ap-south-1.rds.amazonaws.com
  ports:
  - port: 5432


  # devopsdozo-db.devopsdozo.svc.cluster.local