apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: devopsdozo
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: devopsdozo
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==  # postgrespassword
  SECRET_KEY: ZGV2LXNlY3JldC1rZXk=  # dev-secret-key
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzcGFzc3dvcmRAZGV2b3BzZG96by1kYi5kZXZvcHNkb3pvLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZGV2b3BzZG96bw==  # postgresql://postgres:postgrespassword@devopsdozo-db.devopsdozo.svc.cluster.local:5432/devopsdozo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devopsdozo
data:
  DB_HOST: "devopsdozo-db.devopsdozo.svc.cluster.local"
  DB_NAME: "devopsdozo"
  DB_PORT: "5432"
  FLASK_DEBUG: "0"