---
# Create a StorageClass using the EBS CSI Driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
---
# Create a PersistentVolumeClaim using the StorageClass
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-test-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
# Create a test Pod that mounts the PVC
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-test-app
  template:
    metadata:
      labels:
        app: ebs-test-app
    spec:
      containers:
      - name: test-container
        image: nginx:latest
        volumeMounts:
        - name: ebs-volume
          mountPath: /data
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'EBS CSI driver test - $(date)' >> /data/test.txt; sleep 30; done"]
      volumes:
      - name: ebs-volume
        persistentVolumeClaim:
          claimName: ebs-test-claim