apiVersion: v1
kind: Service
metadata:
  name: volume-test-service
  namespace: default
  labels:
    app: volume-test
spec:
  selector:
    app: volume-test
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP