name: Build and push to DockerHub
on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:  # Enable manual triggering

env:
  DOCKERHUB_REPOSITORY: livingdevopswithakhilesh/devopsdozo
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Images to dockerhub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: livingdevopswithakhilesh
          password: ${{ secrets.DOCKERHUB_PAT }}
          
      - name: Build, tag, and push frontend image to Docker Hub
        working-directory: ./frontend
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:frontend-$IMAGE_TAG \
                    --platform=linux/amd64 .
          docker push $DOCKERHUB_REPOSITORY:frontend-$IMAGE_TAG
          echo "Frontend image pushed to Docker Hub: $DOCKERHUB_REPOSITORY:frontend-$IMAGE_TAG"
          
      - name: Build, tag, and push backend image to Docker Hub
        working-directory: ./backend
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:backend-$IMAGE_TAG \
                    --platform=linux/amd64 .
          docker push $DOCKERHUB_REPOSITORY:backend-$IMAGE_TAG
          echo "Backend image pushed to Docker Hub: $DOCKERHUB_REPOSITORY:backend-$IMAGE_TAG"
      
      - name: Summary
        run: |
          echo "### Docker Images Built and Pushed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Frontend: ${{ env.DOCKERHUB_REPOSITORY }}:frontend-${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "✅ Backend: ${{ env.DOCKERHUB_REPOSITORY }}:backend-${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY